version: '2'

services:
  wazuh:
    image: esfateev/wazuh:3.12.3_7.6.2
    hostname: wazuh-manager
    restart: always
    ports:
      - "1514:1514/tcp"
      - "1515:1515"
      - "514:514/udp"
      - "55000:55000"
